name: UI_tests_on_release  
  
on:  
  pull_request:  
    branches:  
      - 'release'  
  
jobs:  
  assemble_ui_test_artifacts:  
    name: Build artifacts  
    runs-on: ubuntu-20.04  
    steps:  
      - uses: actions/checkout@v2  
      - uses: actions/setup-java@v2  
        with:  
          java-version: 18.0.2  
          distribution: 'adopt'  
  
      - name: Grant execute permission to Gradle wrapper  
        run: chmod +x ./gradlew  
  
      - name: Create Google Services JSON File  
        env:  
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}  
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | tr -d '\r' | base64 -d > app/google-services.json  
  
      - name: Build APK for UI test after Unit tests  
        run: |  
          ./gradlew test  
          ./gradlew assembleDebug  
          ./gradlew assembleDebugAndroidTest  
      - name: Upload app-debug APK  
        uses: actions/upload-artifact@v2  
        with:  
          name: app-debug  
          path: app/build/outputs/apk/debug/app-debug.apk  
  
      - name: Upload app-debug-androidTest APK  
        uses: actions/upload-artifact@v2  
        with:  
          name: app-debug-androidTest  
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk  
  
  run_ui_tests_on_firebase:  
    runs-on: ubuntu-20.04  
    needs: assemble_ui_test_artifacts  
    steps:  
      - uses: actions/checkout@v2  
      - name: Download app-debug APK  
        uses: actions/download-artifact@v2  
        with:  
          name: app-debug  
          path: app/build/outputs/apk/debug  
  
      - name: Download app-debug-androidTest APK  
        uses: actions/download-artifact@v2  
        with:  
          name: app-debug-androidTest  
          path: app/build/outputs/apk/androidTest/debug  
  
      - name: Firebase auth with gcloud  
        uses: 'google-github-actions/auth@v1'  
        with:  
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'  
  
      - name: 'Set up Cloud SDK'  
        uses: 'google-github-actions/setup-gcloud@v1'  
  
      - name: 'Use gcloud CLI'  
        run: 'gcloud info'  
  
      - name: Run Instrumentation Tests in Firebase Test Lab  
        run: |  
          gcloud firebase test android models list  
          gcloud firebase test android run 
	          --type instrumentation 
	          --use-orchestrator 
	          --app app/build/outputs/apk/debug/app-debug.apk 
	          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk 
	          --device model=Pixel2,version=28,locale=en,orientation=portrait
